- init.sh
#14 caused some issues when running locally
> Make init.sh idempotent

- .github/workflows/terraform.yml
- main.tf
- modules/common/output.tf
- modules/ilmo/main.tf
- modules/ilmo/variables.tf
- variables.tf
Adding new App Service for Ilmomasiina. Keeping this as draft until we get a database migration system going.
> Add Ilmomasiina

- main.tf
- modules/frontend/output.tf
- modules/ilmo/main.tf
- modules/ilmo/variables.tf
Stuff added in Ilmomasiina 2.0.0-alpha9 (to be merged in https://github.com/Tietokilta/ilmomasiina/pull/90)
> Pass frontend URL to Ilmomasiina

- main.tf
- modules/frontend/main.tf
- modules/histotik/main.tf
- modules/recruiting/storage/main.tf
- modules/tenttiarkisto/main.tf
This PR starts the work for #29. It seems that deprecated resources still work without an update.
> Begin update to Azure provider v3

- main.tf
- modules/common/main.tf
- modules/common/output.tf
- modules/recruiting/ghost/main.tf
- modules/recruiting/ghost/variables.tf
Attempting to remove this piece of manual work (rekry cert renewal).
This PR just adds the ACME cert acquisition, after this has been confirmed to work I'll add another PR to actually use the certs from ACME.
> [part 1/2] Add ACME cert generation on rekry.tietokilta.fi

- .gitignore
- modules/recruiting/storage/main.tf
Part 1 of migrating from single server -> flexible server. Wish me luck.
> Add Mysql flexible server

- modules/recruiting/storage/main.tf
> Bump mysql server to version 8

- modules/recruiting/storage/main.tf
> Add new mysql back

- modules/recruiting/storage/main.tf
> more manual shit

- modules/recruiting/ghost/main.tf
- modules/recruiting/storage/output.tf
> Update ghost version, move to new mysql

- modules/recruiting/ghost/main.tf
> Update ghost to latest 5.38

- modules/recruiting/storage/main.tf
> Remove old mysql instance

- main.tf
- modules/common/main.tf
- modules/common/output.tf
- modules/keyvault/main.tf
- modules/keyvault/output.tf
- modules/web/app/dns.tf
- modules/web/app/main.tf
- modules/web/app/outputs.tf
- modules/web/app/variables.tf
- modules/web/storage/main.tf
- modules/web/storage/output.tf
- modules/web/storage/variables.tf
Infra for deploying https://github.com/Tietokilta/web
> new web infra

- main.tf
> Change mailgun account for rekry TiK

- main.tf
> Mailgun merge part 2

- modules/web/main.tf
Enable http2 for speed improvements
> enable http2 for cms and web

- main.tf
- modules/keyvault/main.tf
- modules/keyvault/output.tf
- modules/web/main.tf
- modules/web/variables.tf
Add specs for digitransit subscription key a.k.a. hsl api key for info screen
> Add digitransit subscription key

- main.tf
- modules/web/main.tf
- modules/web/variables.tf
Add URL env variable to web for laskugeneraattori
> feat: add URL for laskugeneraattori

- modules/invoicing/main.tf
This should be merged together with the deployment of https://github.com/Tietokilta/laskugeneraattori/pull/25
> feat: add new invoice app settings

- .devcontainer.json
- .envrc
- .gitignore
- flake.lock
- flake.nix
This is a QoL improvement for Nix users, others may think I'm infecting the repo with Nix :man_shrugging:
> feat: add flake.nix and Dev Container configuration

- modules/m0/dns.tf
- modules/m0/main.tf
The page is not yet finished for this year, so it should not be public
> feat: Temporarily disable A record for M0

- main.tf
- modules/oldweb/main.tf
- modules/oldweb/variables.tf
Preparations for migrating oldweb to Azure:
- Add postgres database for oldweb
- Add containre registry for uploading oldweb image
- Create file share for oldweb pictures etc.
> feat: Preparations for oldweb

- main.tf
- modules/oldweb/main.tf
- modules/oldweb/outputs.tf
- modules/oldweb/variables.tf
This PR (hopefully) runs oldweb in Azure (not yet in `old.tietokilta.fi`)
> feat: Create oldweb app to Azure

- modules/oldweb/main.tf
Created admin cred for ACR, so that oldweb can pull the image using those credentials
> fix: Add auth for accessing ACR for oldweb

- main.tf
- modules/ilmo/main.tf
- modules/ilmo_staging/main.tf
- modules/ilmo_staging/variables.tf
- add lightweight staging env for ilmo
- remove redundant module vars
- remove deprecated DOCKER_REGISTRY_SERVER_URL
- fix ADMIN_URL
> feat(ilmo): fixes to config and new staging env

- main.tf
- modules/isopistekortti/main.tf
- modules/isopistekortti/output.tf
- modules/isopistekortti/variables.tf
- status/config.yaml
Adds the ISOpistekortti web app at ISO.tietokilta.fi. No clue if what I've done is right
> feat: add isopistekortti
